version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - npm install gitbook-cli -g
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - gitbook install
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - gitbook build
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
      - aws s3 sync _book/ s3://im-joeshi-aws/iot/ --delete --exclude ".git/*"
      - aws cloudfront create-invalidation --distribution-id E2D6JGIECXYGAG --path /iot/*
artifacts:
  files:
    - _book/**/*
  discard-paths: yes
